/* tslint:disable */
/* eslint-disable */
/**
 * ISOK API
 * Openapi of isok api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiCheckMetricsResult
 */
export interface ApiCheckMetricsResult {
    /**
     * 
     * @type {number}
     * @memberof ApiCheckMetricsResult
     */
    latency: number;
}

/**
 * Check if a given object implements the ApiCheckMetricsResult interface.
 */
export function instanceOfApiCheckMetricsResult(value: object): value is ApiCheckMetricsResult {
    if (!('latency' in value) || value['latency'] === undefined) return false;
    return true;
}

export function ApiCheckMetricsResultFromJSON(json: any): ApiCheckMetricsResult {
    return ApiCheckMetricsResultFromJSONTyped(json, false);
}

export function ApiCheckMetricsResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiCheckMetricsResult {
    if (json == null) {
        return json;
    }
    return {
        
        'latency': json['latency'],
    };
}

export function ApiCheckMetricsResultToJSON(json: any): ApiCheckMetricsResult {
    return ApiCheckMetricsResultToJSONTyped(json, false);
}

export function ApiCheckMetricsResultToJSONTyped(value?: ApiCheckMetricsResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'latency': value['latency'],
    };
}

