/* tslint:disable */
/* eslint-disable */
/**
 * ISOK API
 * Openapi of isok api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CheckResultDetails } from './CheckResultDetails';
import {
    CheckResultDetailsFromJSON,
    CheckResultDetailsFromJSONTyped,
    CheckResultDetailsToJSON,
    CheckResultDetailsToJSONTyped,
} from './CheckResultDetails';
import type { CheckStatus } from './CheckStatus';
import {
    CheckStatusFromJSON,
    CheckStatusFromJSONTyped,
    CheckStatusToJSON,
    CheckStatusToJSONTyped,
} from './CheckStatus';
import type { CheckMetrics } from './CheckMetrics';
import {
    CheckMetricsFromJSON,
    CheckMetricsFromJSONTyped,
    CheckMetricsToJSON,
    CheckMetricsToJSONTyped,
} from './CheckMetrics';

/**
 * 
 * @export
 * @interface ApiCheckResult
 */
export interface ApiCheckResult {
    /**
     * 
     * @type {CheckResultDetails}
     * @memberof ApiCheckResult
     */
    details: CheckResultDetails;
    /**
     * 
     * @type {Date}
     * @memberof ApiCheckResult
     */
    end: Date;
    /**
     * 
     * @type {string}
     * @memberof ApiCheckResult
     */
    error?: string | null;
    /**
     * 
     * @type {CheckMetrics}
     * @memberof ApiCheckResult
     */
    metrics: CheckMetrics;
    /**
     * 
     * @type {Date}
     * @memberof ApiCheckResult
     */
    start: Date;
    /**
     * 
     * @type {CheckStatus}
     * @memberof ApiCheckResult
     */
    status: CheckStatus;
}



/**
 * Check if a given object implements the ApiCheckResult interface.
 */
export function instanceOfApiCheckResult(value: object): value is ApiCheckResult {
    if (!('details' in value) || value['details'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    if (!('metrics' in value) || value['metrics'] === undefined) return false;
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ApiCheckResultFromJSON(json: any): ApiCheckResult {
    return ApiCheckResultFromJSONTyped(json, false);
}

export function ApiCheckResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiCheckResult {
    if (json == null) {
        return json;
    }
    return {
        
        'details': CheckResultDetailsFromJSON(json['details']),
        'end': (new Date(json['end'])),
        'error': json['error'] == null ? undefined : json['error'],
        'metrics': CheckMetricsFromJSON(json['metrics']),
        'start': (new Date(json['start'])),
        'status': CheckStatusFromJSON(json['status']),
    };
}

export function ApiCheckResultToJSON(json: any): ApiCheckResult {
    return ApiCheckResultToJSONTyped(json, false);
}

export function ApiCheckResultToJSONTyped(value?: ApiCheckResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'details': CheckResultDetailsToJSON(value['details']),
        'end': ((value['end']).toISOString()),
        'error': value['error'],
        'metrics': CheckMetricsToJSON(value['metrics']),
        'start': ((value['start']).toISOString()),
        'status': CheckStatusToJSON(value['status']),
    };
}

