/* tslint:disable */
/* eslint-disable */
/**
 * ISOK API
 * Openapi of isok api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CheckZone } from './CheckZone';
import {
    CheckZoneFromJSON,
    CheckZoneFromJSONTyped,
    CheckZoneToJSON,
    CheckZoneToJSONTyped,
} from './CheckZone';
import type { CheckKind } from './CheckKind';
import {
    CheckKindFromJSON,
    CheckKindFromJSONTyped,
    CheckKindToJSON,
    CheckKindToJSONTyped,
} from './CheckKind';
import type { Duration } from './Duration';
import {
    DurationFromJSON,
    DurationFromJSONTyped,
    DurationToJSON,
    DurationToJSONTyped,
} from './Duration';

/**
 * 
 * @export
 * @interface ApiCheckInput
 */
export interface ApiCheckInput {
    /**
     * 
     * @type {Duration}
     * @memberof ApiCheckInput
     */
    interval: Duration;
    /**
     * 
     * @type {CheckKind}
     * @memberof ApiCheckInput
     */
    kind: CheckKind;
    /**
     * 
     * @type {string}
     * @memberof ApiCheckInput
     */
    name: string;
    /**
     * 
     * @type {Array<CheckZone>}
     * @memberof ApiCheckInput
     */
    zones: Array<CheckZone>;
}

/**
 * Check if a given object implements the ApiCheckInput interface.
 */
export function instanceOfApiCheckInput(value: object): value is ApiCheckInput {
    if (!('interval' in value) || value['interval'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('zones' in value) || value['zones'] === undefined) return false;
    return true;
}

export function ApiCheckInputFromJSON(json: any): ApiCheckInput {
    return ApiCheckInputFromJSONTyped(json, false);
}

export function ApiCheckInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiCheckInput {
    if (json == null) {
        return json;
    }
    return {
        
        'interval': DurationFromJSON(json['interval']),
        'kind': CheckKindFromJSON(json['kind']),
        'name': json['name'],
        'zones': ((json['zones'] as Array<any>).map(CheckZoneFromJSON)),
    };
}

export function ApiCheckInputToJSON(json: any): ApiCheckInput {
    return ApiCheckInputToJSONTyped(json, false);
}

export function ApiCheckInputToJSONTyped(value?: ApiCheckInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'interval': DurationToJSON(value['interval']),
        'kind': CheckKindToJSON(value['kind']),
        'name': value['name'],
        'zones': ((value['zones'] as Array<any>).map(CheckZoneToJSON)),
    };
}

