/* tslint:disable */
/* eslint-disable */
/**
 * ISOK API
 * Openapi of isok api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckMetrics
 */
export interface CheckMetrics {
    /**
     * 
     * @type {number}
     * @memberof CheckMetrics
     */
    latency: number;
}

/**
 * Check if a given object implements the CheckMetrics interface.
 */
export function instanceOfCheckMetrics(value: object): value is CheckMetrics {
    if (!('latency' in value) || value['latency'] === undefined) return false;
    return true;
}

export function CheckMetricsFromJSON(json: any): CheckMetrics {
    return CheckMetricsFromJSONTyped(json, false);
}

export function CheckMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'latency': json['latency'],
    };
}

export function CheckMetricsToJSON(json: any): CheckMetrics {
    return CheckMetricsToJSONTyped(json, false);
}

export function CheckMetricsToJSONTyped(value?: CheckMetrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'latency': value['latency'],
    };
}

