/* tslint:disable */
/* eslint-disable */
/**
 * ISOK API
 * Openapi of isok api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckZoneOneOf
 */
export interface CheckZoneOneOf {
    /**
     * 
     * @type {string}
     * @memberof CheckZoneOneOf
     */
    region: string;
}

/**
 * Check if a given object implements the CheckZoneOneOf interface.
 */
export function instanceOfCheckZoneOneOf(value: object): value is CheckZoneOneOf {
    if (!('region' in value) || value['region'] === undefined) return false;
    return true;
}

export function CheckZoneOneOfFromJSON(json: any): CheckZoneOneOf {
    return CheckZoneOneOfFromJSONTyped(json, false);
}

export function CheckZoneOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckZoneOneOf {
    if (json == null) {
        return json;
    }
    return {

        'region': json['region'],
    };
}

export function CheckZoneOneOfToJSON(json: any): CheckZoneOneOf {
    return CheckZoneOneOfToJSONTyped(json, false);
}

export function CheckZoneOneOfToJSONTyped(value?: CheckZoneOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'region': value['region'],
    };
}

