/* tslint:disable */
/* eslint-disable */
/**
 * ISOK API
 * Openapi of isok api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HttpCheck } from './HttpCheck';
import {
    HttpCheckFromJSON,
    HttpCheckFromJSONTyped,
    HttpCheckToJSON,
    HttpCheckToJSONTyped,
} from './HttpCheck';

/**
 * 
 * @export
 * @interface CheckKind
 */
export interface CheckKind {
    /**
     * 
     * @type {HttpCheck}
     * @memberof CheckKind
     */
    http: HttpCheck;
}

/**
 * Check if a given object implements the CheckKind interface.
 */
export function instanceOfCheckKind(value: object): value is CheckKind {
    if (!('http' in value) || value['http'] === undefined) return false;
    return true;
}

export function CheckKindFromJSON(json: any): CheckKind {
    return CheckKindFromJSONTyped(json, false);
}

export function CheckKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckKind {
    if (json == null) {
        return json;
    }
    return {
        
        'http': HttpCheckFromJSON(json['Http']),
    };
}

export function CheckKindToJSON(json: any): CheckKind {
    return CheckKindToJSONTyped(json, false);
}

export function CheckKindToJSONTyped(value?: CheckKind | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Http': HttpCheckToJSON(value['http']),
    };
}

