/* tslint:disable */
/* eslint-disable */
/**
 * ISOK API
 * Openapi of isok api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CheckSchemaTextInputVariant = {
    Text: 'Text',
    Url: 'Url',
    Area: 'Area'
} as const;
export type CheckSchemaTextInputVariant = typeof CheckSchemaTextInputVariant[keyof typeof CheckSchemaTextInputVariant];


export function instanceOfCheckSchemaTextInputVariant(value: any): boolean {
    for (const key in CheckSchemaTextInputVariant) {
        if (Object.prototype.hasOwnProperty.call(CheckSchemaTextInputVariant, key)) {
            if (CheckSchemaTextInputVariant[key as keyof typeof CheckSchemaTextInputVariant] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CheckSchemaTextInputVariantFromJSON(json: any): CheckSchemaTextInputVariant {
    return CheckSchemaTextInputVariantFromJSONTyped(json, false);
}

export function CheckSchemaTextInputVariantFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckSchemaTextInputVariant {
    return json as CheckSchemaTextInputVariant;
}

export function CheckSchemaTextInputVariantToJSON(value?: CheckSchemaTextInputVariant | null): any {
    return value as any;
}

export function CheckSchemaTextInputVariantToJSONTyped(value: any, ignoreDiscriminator: boolean): CheckSchemaTextInputVariant {
    return value as CheckSchemaTextInputVariant;
}

