/* tslint:disable */
/* eslint-disable */
/**
 * ISOK API
 * Openapi of isok api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CheckZoneOneOf } from './CheckZoneOneOf';
import {
    instanceOfCheckZoneOneOf,
    CheckZoneOneOfFromJSON,
    CheckZoneOneOfFromJSONTyped,
    CheckZoneOneOfToJSON,
} from './CheckZoneOneOf';
import type { CheckZoneOneOf1 } from './CheckZoneOneOf1';
import {
    instanceOfCheckZoneOneOf1,
    CheckZoneOneOf1FromJSON,
    CheckZoneOneOf1FromJSONTyped,
    CheckZoneOneOf1ToJSON,
} from './CheckZoneOneOf1';

/**
 * @type CheckZone
 * 
 * @export
 */
export type CheckZone = CheckZoneOneOf | CheckZoneOneOf1 | string;

export function CheckZoneFromJSON(json: any): CheckZone {
    return CheckZoneFromJSONTyped(json, false);
}

export function CheckZoneFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckZone {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfCheckZoneOneOf(json)) {
        return CheckZoneOneOfFromJSONTyped(json, true);
    }
    if (instanceOfCheckZoneOneOf1(json)) {
        return CheckZoneOneOf1FromJSONTyped(json, true);
    }

    return {} as any;
}

export function CheckZoneToJSON(json: any): any {
    return CheckZoneToJSONTyped(json, false);
}

export function CheckZoneToJSONTyped(value?: CheckZone | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfCheckZoneOneOf(value)) {
        return CheckZoneOneOfToJSON(value as CheckZoneOneOf);
    }
    if (instanceOfCheckZoneOneOf1(value)) {
        return CheckZoneOneOf1ToJSON(value as CheckZoneOneOf1);
    }

    return {};
}

