/* tslint:disable */
/* eslint-disable */
/**
 * ISOK API
 * Openapi of isok api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CheckSchemaInputKind } from './CheckSchemaInputKind';
import {
    CheckSchemaInputKindFromJSON,
    CheckSchemaInputKindFromJSONTyped,
    CheckSchemaInputKindToJSON,
    CheckSchemaInputKindToJSONTyped,
} from './CheckSchemaInputKind';

/**
 * 
 * @export
 * @interface CheckSchemaInput
 */
export interface CheckSchemaInput {
    /**
     * 
     * @type {CheckSchemaInputKind}
     * @memberof CheckSchemaInput
     */
    kind: CheckSchemaInputKind;
    /**
     * 
     * @type {string}
     * @memberof CheckSchemaInput
     */
    title: string;
}

/**
 * Check if a given object implements the CheckSchemaInput interface.
 */
export function instanceOfCheckSchemaInput(value: object): value is CheckSchemaInput {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function CheckSchemaInputFromJSON(json: any): CheckSchemaInput {
    return CheckSchemaInputFromJSONTyped(json, false);
}

export function CheckSchemaInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckSchemaInput {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': CheckSchemaInputKindFromJSON(json['kind']),
        'title': json['title'],
    };
}

export function CheckSchemaInputToJSON(json: any): CheckSchemaInput {
    return CheckSchemaInputToJSONTyped(json, false);
}

export function CheckSchemaInputToJSONTyped(value?: CheckSchemaInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': CheckSchemaInputKindToJSON(value['kind']),
        'title': value['title'],
    };
}

