/* tslint:disable */
/* eslint-disable */
/**
 * ISOK API
 * Openapi of isok api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HttpCheckResult } from './HttpCheckResult';
import {
    HttpCheckResultFromJSON,
    HttpCheckResultFromJSONTyped,
    HttpCheckResultToJSON,
    HttpCheckResultToJSONTyped,
} from './HttpCheckResult';

/**
 * 
 * @export
 * @interface CheckResultDetails
 */
export interface CheckResultDetails {
    /**
     * 
     * @type {HttpCheckResult}
     * @memberof CheckResultDetails
     */
    http: HttpCheckResult;
}

/**
 * Check if a given object implements the CheckResultDetails interface.
 */
export function instanceOfCheckResultDetails(value: object): value is CheckResultDetails {
    if (!('http' in value) || value['http'] === undefined) return false;
    return true;
}

export function CheckResultDetailsFromJSON(json: any): CheckResultDetails {
    return CheckResultDetailsFromJSONTyped(json, false);
}

export function CheckResultDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckResultDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'http': HttpCheckResultFromJSON(json['Http']),
    };
}

export function CheckResultDetailsToJSON(json: any): CheckResultDetails {
    return CheckResultDetailsToJSONTyped(json, false);
}

export function CheckResultDetailsToJSONTyped(value?: CheckResultDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Http': HttpCheckResultToJSON(value['http']),
    };
}

