/* tslint:disable */
/* eslint-disable */
/**
 * ISOK API
 * Openapi of isok api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckZoneOneOf1
 */
export interface CheckZoneOneOf1 {
    /**
     * 
     * @type {string}
     * @memberof CheckZoneOneOf1
     */
    zone: string;
}

/**
 * Check if a given object implements the CheckZoneOneOf1 interface.
 */
export function instanceOfCheckZoneOneOf1(value: object): value is CheckZoneOneOf1 {
    if (!('zone' in value) || value['zone'] === undefined) return false;
    return true;
}

export function CheckZoneOneOf1FromJSON(json: any): CheckZoneOneOf1 {
    return CheckZoneOneOf1FromJSONTyped(json, false);
}

export function CheckZoneOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckZoneOneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'zone': json['Zone'],
    };
}

export function CheckZoneOneOf1ToJSON(json: any): CheckZoneOneOf1 {
    return CheckZoneOneOf1ToJSONTyped(json, false);
}

export function CheckZoneOneOf1ToJSONTyped(value?: CheckZoneOneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Zone': value['zone'],
    };
}

