/* tslint:disable */
/* eslint-disable */
/**
 * ISOK API
 * Openapi of isok api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CheckStatus = {
    Unknown: 'Unknown',
    Reachable: 'Reachable',
    Unreachable: 'Unreachable',
    Timeout: 'Timeout'
} as const;
export type CheckStatus = typeof CheckStatus[keyof typeof CheckStatus];


export function instanceOfCheckStatus(value: any): boolean {
    for (const key in CheckStatus) {
        if (Object.prototype.hasOwnProperty.call(CheckStatus, key)) {
            if (CheckStatus[key as keyof typeof CheckStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CheckStatusFromJSON(json: any): CheckStatus {
    return CheckStatusFromJSONTyped(json, false);
}

export function CheckStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckStatus {
    return json as CheckStatus;
}

export function CheckStatusToJSON(value?: CheckStatus | null): any {
    return value as any;
}

export function CheckStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): CheckStatus {
    return value as CheckStatus;
}

