/* tslint:disable */
/* eslint-disable */
/**
 * ISOK API
 * Openapi of isok api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CheckSchemaInputKindOneOf } from './CheckSchemaInputKindOneOf';
import {
    instanceOfCheckSchemaInputKindOneOf,
    CheckSchemaInputKindOneOfFromJSON,
    CheckSchemaInputKindOneOfFromJSONTyped,
    CheckSchemaInputKindOneOfToJSON,
} from './CheckSchemaInputKindOneOf';
import type { CheckSchemaInputKindOneOf1 } from './CheckSchemaInputKindOneOf1';
import {
    instanceOfCheckSchemaInputKindOneOf1,
    CheckSchemaInputKindOneOf1FromJSON,
    CheckSchemaInputKindOneOf1FromJSONTyped,
    CheckSchemaInputKindOneOf1ToJSON,
} from './CheckSchemaInputKindOneOf1';
import type { CheckSchemaInputKindOneOf2 } from './CheckSchemaInputKindOneOf2';
import {
    instanceOfCheckSchemaInputKindOneOf2,
    CheckSchemaInputKindOneOf2FromJSON,
    CheckSchemaInputKindOneOf2FromJSONTyped,
    CheckSchemaInputKindOneOf2ToJSON,
} from './CheckSchemaInputKindOneOf2';

/**
 * @type CheckSchemaInputKind
 * 
 * @export
 */
export type CheckSchemaInputKind = CheckSchemaInputKindOneOf | CheckSchemaInputKindOneOf1 | CheckSchemaInputKindOneOf2;

export function CheckSchemaInputKindFromJSON(json: any): CheckSchemaInputKind {
    return CheckSchemaInputKindFromJSONTyped(json, false);
}

export function CheckSchemaInputKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckSchemaInputKind {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfCheckSchemaInputKindOneOf(json)) {
        return CheckSchemaInputKindOneOfFromJSONTyped(json, true);
    }
    if (instanceOfCheckSchemaInputKindOneOf1(json)) {
        return CheckSchemaInputKindOneOf1FromJSONTyped(json, true);
    }
    if (instanceOfCheckSchemaInputKindOneOf2(json)) {
        return CheckSchemaInputKindOneOf2FromJSONTyped(json, true);
    }

    return {} as any;
}

export function CheckSchemaInputKindToJSON(json: any): any {
    return CheckSchemaInputKindToJSONTyped(json, false);
}

export function CheckSchemaInputKindToJSONTyped(value?: CheckSchemaInputKind | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfCheckSchemaInputKindOneOf(value)) {
        return CheckSchemaInputKindOneOfToJSON(value as CheckSchemaInputKindOneOf);
    }
    if (instanceOfCheckSchemaInputKindOneOf1(value)) {
        return CheckSchemaInputKindOneOf1ToJSON(value as CheckSchemaInputKindOneOf1);
    }
    if (instanceOfCheckSchemaInputKindOneOf2(value)) {
        return CheckSchemaInputKindOneOf2ToJSON(value as CheckSchemaInputKindOneOf2);
    }

    return {};
}

