/* tslint:disable */
/* eslint-disable */
/**
 * ISOK API
 * Openapi of isok api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CheckSchemaCheckKind = {
    Http: 'Http'
} as const;
export type CheckSchemaCheckKind = typeof CheckSchemaCheckKind[keyof typeof CheckSchemaCheckKind];


export function instanceOfCheckSchemaCheckKind(value: any): boolean {
    for (const key in CheckSchemaCheckKind) {
        if (Object.prototype.hasOwnProperty.call(CheckSchemaCheckKind, key)) {
            if (CheckSchemaCheckKind[key as keyof typeof CheckSchemaCheckKind] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CheckSchemaCheckKindFromJSON(json: any): CheckSchemaCheckKind {
    return CheckSchemaCheckKindFromJSONTyped(json, false);
}

export function CheckSchemaCheckKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckSchemaCheckKind {
    return json as CheckSchemaCheckKind;
}

export function CheckSchemaCheckKindToJSON(value?: CheckSchemaCheckKind | null): any {
    return value as any;
}

export function CheckSchemaCheckKindToJSONTyped(value: any, ignoreDiscriminator: boolean): CheckSchemaCheckKind {
    return value as CheckSchemaCheckKind;
}

