/* tslint:disable */
/* eslint-disable */
/**
 * ISOK API
 * Openapi of isok api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CheckSchemaSelectInputOption } from './CheckSchemaSelectInputOption';
import {
    CheckSchemaSelectInputOptionFromJSON,
    CheckSchemaSelectInputOptionFromJSONTyped,
    CheckSchemaSelectInputOptionToJSON,
    CheckSchemaSelectInputOptionToJSONTyped,
} from './CheckSchemaSelectInputOption';

/**
 * 
 * @export
 * @interface CheckSchemaInputKindOneOf1
 */
export interface CheckSchemaInputKindOneOf1 {
    /**
     * 
     * @type {Array<CheckSchemaSelectInputOption>}
     * @memberof CheckSchemaInputKindOneOf1
     */
    selectOptions: Array<CheckSchemaSelectInputOption>;
    /**
     * 
     * @type {string}
     * @memberof CheckSchemaInputKindOneOf1
     */
    type: CheckSchemaInputKindOneOf1TypeEnum;
}


/**
 * @export
 */
export const CheckSchemaInputKindOneOf1TypeEnum = {
    Select: 'Select'
} as const;
export type CheckSchemaInputKindOneOf1TypeEnum = typeof CheckSchemaInputKindOneOf1TypeEnum[keyof typeof CheckSchemaInputKindOneOf1TypeEnum];


/**
 * Check if a given object implements the CheckSchemaInputKindOneOf1 interface.
 */
export function instanceOfCheckSchemaInputKindOneOf1(value: object): value is CheckSchemaInputKindOneOf1 {
    if (!('selectOptions' in value) || value['selectOptions'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function CheckSchemaInputKindOneOf1FromJSON(json: any): CheckSchemaInputKindOneOf1 {
    return CheckSchemaInputKindOneOf1FromJSONTyped(json, false);
}

export function CheckSchemaInputKindOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckSchemaInputKindOneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'selectOptions': ((json['selectOptions'] as Array<any>).map(CheckSchemaSelectInputOptionFromJSON)),
        'type': json['type'],
    };
}

export function CheckSchemaInputKindOneOf1ToJSON(json: any): CheckSchemaInputKindOneOf1 {
    return CheckSchemaInputKindOneOf1ToJSONTyped(json, false);
}

export function CheckSchemaInputKindOneOf1ToJSONTyped(value?: CheckSchemaInputKindOneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'selectOptions': ((value['selectOptions'] as Array<any>).map(CheckSchemaSelectInputOptionToJSON)),
        'type': value['type'],
    };
}

