/* tslint:disable */
/* eslint-disable */
/**
 * ISOK API
 * Openapi of isok api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckSchemaSelectInputOption
 */
export interface CheckSchemaSelectInputOption {
    /**
     * 
     * @type {string}
     * @memberof CheckSchemaSelectInputOption
     */
    label: string;
    /**
     * 
     * @type {string}
     * @memberof CheckSchemaSelectInputOption
     */
    value: string;
}

/**
 * Check if a given object implements the CheckSchemaSelectInputOption interface.
 */
export function instanceOfCheckSchemaSelectInputOption(value: object): value is CheckSchemaSelectInputOption {
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function CheckSchemaSelectInputOptionFromJSON(json: any): CheckSchemaSelectInputOption {
    return CheckSchemaSelectInputOptionFromJSONTyped(json, false);
}

export function CheckSchemaSelectInputOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckSchemaSelectInputOption {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'],
        'value': json['value'],
    };
}

export function CheckSchemaSelectInputOptionToJSON(json: any): CheckSchemaSelectInputOption {
    return CheckSchemaSelectInputOptionToJSONTyped(json, false);
}

export function CheckSchemaSelectInputOptionToJSONTyped(value?: CheckSchemaSelectInputOption | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'],
        'value': value['value'],
    };
}

