/* tslint:disable */
/* eslint-disable */
/**
 * ISOK API
 * Openapi of isok api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Creds
 */
export interface Creds {
    /**
     * 
     * @type {string}
     * @memberof Creds
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof Creds
     */
    password: string;
}

/**
 * Check if a given object implements the Creds interface.
 */
export function instanceOfCreds(value: object): value is Creds {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function CredsFromJSON(json: any): Creds {
    return CredsFromJSONTyped(json, false);
}

export function CredsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Creds {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function CredsToJSON(json: any): Creds {
    return CredsToJSONTyped(json, false);
}

export function CredsToJSONTyped(value?: Creds | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

