/* tslint:disable */
/* eslint-disable */
/**
 * ISOK API
 * Openapi of isok api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Duration
 */
export interface Duration {
    /**
     * 
     * @type {number}
     * @memberof Duration
     */
    nanos: number;
    /**
     * 
     * @type {number}
     * @memberof Duration
     */
    secs: number;
}

/**
 * Check if a given object implements the Duration interface.
 */
export function instanceOfDuration(value: object): value is Duration {
    if (!('nanos' in value) || value['nanos'] === undefined) return false;
    if (!('secs' in value) || value['secs'] === undefined) return false;
    return true;
}

export function DurationFromJSON(json: any): Duration {
    return DurationFromJSONTyped(json, false);
}

export function DurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Duration {
    if (json == null) {
        return json;
    }
    return {
        
        'nanos': json['nanos'],
        'secs': json['secs'],
    };
}

export function DurationToJSON(json: any): Duration {
    return DurationToJSONTyped(json, false);
}

export function DurationToJSONTyped(value?: Duration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nanos': value['nanos'],
        'secs': value['secs'],
    };
}

