/* tslint:disable */
/* eslint-disable */
/**
 * ISOK API
 * Openapi of isok api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiCheckStatus } from './ApiCheckStatus';
import {
    ApiCheckStatusFromJSON,
    ApiCheckStatusFromJSONTyped,
    ApiCheckStatusToJSON,
    ApiCheckStatusToJSONTyped,
} from './ApiCheckStatus';
import type { CheckResultDetails } from './CheckResultDetails';
import {
    CheckResultDetailsFromJSON,
    CheckResultDetailsFromJSONTyped,
    CheckResultDetailsToJSON,
    CheckResultDetailsToJSONTyped,
} from './CheckResultDetails';
import type { ApiCheckResult } from './ApiCheckResult';
import {
    ApiCheckResultFromJSON,
    ApiCheckResultFromJSONTyped,
    ApiCheckResultToJSON,
    ApiCheckResultToJSONTyped,
} from './ApiCheckResult';
import type { CheckMetrics } from './CheckMetrics';
import {
    CheckMetricsFromJSON,
    CheckMetricsFromJSONTyped,
    CheckMetricsToJSON,
    CheckMetricsToJSONTyped,
} from './CheckMetrics';

/**
 * 
 * @export
 * @interface GetChecksSummaryV1200ResponseValueInner
 */
export interface GetChecksSummaryV1200ResponseValueInner {
    /**
     * 
     * @type {CheckResultDetails}
     * @memberof GetChecksSummaryV1200ResponseValueInner
     */
    details: CheckResultDetails;
    /**
     * 
     * @type {Date}
     * @memberof GetChecksSummaryV1200ResponseValueInner
     */
    end: Date;
    /**
     * 
     * @type {string}
     * @memberof GetChecksSummaryV1200ResponseValueInner
     */
    error?: string;
    /**
     * 
     * @type {CheckMetrics}
     * @memberof GetChecksSummaryV1200ResponseValueInner
     */
    metrics: CheckMetrics;
    /**
     * 
     * @type {Date}
     * @memberof GetChecksSummaryV1200ResponseValueInner
     */
    start: Date;
    /**
     * 
     * @type {ApiCheckStatus}
     * @memberof GetChecksSummaryV1200ResponseValueInner
     */
    status: ApiCheckStatus;
}



/**
 * Check if a given object implements the GetChecksSummaryV1200ResponseValueInner interface.
 */
export function instanceOfGetChecksSummaryV1200ResponseValueInner(value: object): value is GetChecksSummaryV1200ResponseValueInner {
    if (!('details' in value) || value['details'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    if (!('metrics' in value) || value['metrics'] === undefined) return false;
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function GetChecksSummaryV1200ResponseValueInnerFromJSON(json: any): GetChecksSummaryV1200ResponseValueInner {
    return GetChecksSummaryV1200ResponseValueInnerFromJSONTyped(json, false);
}

export function GetChecksSummaryV1200ResponseValueInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetChecksSummaryV1200ResponseValueInner {
    if (json == null) {
        return json;
    }
    return {
        
        'details': CheckResultDetailsFromJSON(json['details']),
        'end': (new Date(json['end'])),
        'error': json['error'] == null ? undefined : json['error'],
        'metrics': CheckMetricsFromJSON(json['metrics']),
        'start': (new Date(json['start'])),
        'status': ApiCheckStatusFromJSON(json['status']),
    };
}

export function GetChecksSummaryV1200ResponseValueInnerToJSON(json: any): GetChecksSummaryV1200ResponseValueInner {
    return GetChecksSummaryV1200ResponseValueInnerToJSONTyped(json, false);
}

export function GetChecksSummaryV1200ResponseValueInnerToJSONTyped(value?: GetChecksSummaryV1200ResponseValueInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'details': CheckResultDetailsToJSON(value['details']),
        'end': ((value['end']).toISOString()),
        'error': value['error'],
        'metrics': CheckMetricsToJSON(value['metrics']),
        'start': ((value['start']).toISOString()),
        'status': ApiCheckStatusToJSON(value['status']),
    };
}

