/* tslint:disable */
/* eslint-disable */
/**
 * ISOK API
 * Openapi of isok api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HttpCheck
 */
export interface HttpCheck {
    /**
     * 
     * @type {string}
     * @memberof HttpCheck
     */
    body?: string | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof HttpCheck
     */
    headers: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof HttpCheck
     */
    method: string;
    /**
     * 
     * @type {string}
     * @memberof HttpCheck
     */
    url: string;
}

/**
 * Check if a given object implements the HttpCheck interface.
 */
export function instanceOfHttpCheck(value: object): value is HttpCheck {
    if (!('headers' in value) || value['headers'] === undefined) return false;
    if (!('method' in value) || value['method'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function HttpCheckFromJSON(json: any): HttpCheck {
    return HttpCheckFromJSONTyped(json, false);
}

export function HttpCheckFromJSONTyped(json: any, ignoreDiscriminator: boolean): HttpCheck {
    if (json == null) {
        return json;
    }
    return {
        
        'body': json['body'] == null ? undefined : json['body'],
        'headers': json['headers'],
        'method': json['method'],
        'url': json['url'],
    };
}

export function HttpCheckToJSON(json: any): HttpCheck {
    return HttpCheckToJSONTyped(json, false);
}

export function HttpCheckToJSONTyped(value?: HttpCheck | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'body': value['body'],
        'headers': value['headers'],
        'method': value['method'],
        'url': value['url'],
    };
}

