/* tslint:disable */
/* eslint-disable */
/**
 * ISOK API
 * Openapi of isok api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HttpCheckResult
 */
export interface HttpCheckResult {
    /**
     * 
     * @type {number}
     * @memberof HttpCheckResult
     */
    statusCode: number;
}

/**
 * Check if a given object implements the HttpCheckResult interface.
 */
export function instanceOfHttpCheckResult(value: object): value is HttpCheckResult {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    return true;
}

export function HttpCheckResultFromJSON(json: any): HttpCheckResult {
    return HttpCheckResultFromJSONTyped(json, false);
}

export function HttpCheckResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): HttpCheckResult {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['status_code'],
    };
}

export function HttpCheckResultToJSON(json: any): HttpCheckResult {
    return HttpCheckResultToJSONTyped(json, false);
}

export function HttpCheckResultToJSONTyped(value?: HttpCheckResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status_code': value['statusCode'],
    };
}

