/* tslint:disable */
/* eslint-disable */
/**
 * ISOK API
 * Openapi of isok api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganisationInput
 */
export interface OrganisationInput {
    /**
     * 
     * @type {string}
     * @memberof OrganisationInput
     */
    name: string;
}

/**
 * Check if a given object implements the OrganisationInput interface.
 */
export function instanceOfOrganisationInput(value: object): value is OrganisationInput {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function OrganisationInputFromJSON(json: any): OrganisationInput {
    return OrganisationInputFromJSONTyped(json, false);
}

export function OrganisationInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationInput {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function OrganisationInputToJSON(json: any): OrganisationInput {
    return OrganisationInputToJSONTyped(json, false);
}

export function OrganisationInputToJSONTyped(value?: OrganisationInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

