/* tslint:disable */
/* eslint-disable */
/**
 * ISOK API
 * Openapi of isok api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganisationPath
 */
export interface OrganisationPath {
    /**
     * 
     * @type {string}
     * @memberof OrganisationPath
     */
    organisationId: string;
}

/**
 * Check if a given object implements the OrganisationPath interface.
 */
export function instanceOfOrganisationPath(value: object): value is OrganisationPath {
    if (!('organisationId' in value) || value['organisationId'] === undefined) return false;
    return true;
}

export function OrganisationPathFromJSON(json: any): OrganisationPath {
    return OrganisationPathFromJSONTyped(json, false);
}

export function OrganisationPathFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationPath {
    if (json == null) {
        return json;
    }
    return {
        
        'organisationId': json['organisation_id'],
    };
}

export function OrganisationPathToJSON(json: any): OrganisationPath {
    return OrganisationPathToJSONTyped(json, false);
}

export function OrganisationPathToJSONTyped(value?: OrganisationPath | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organisation_id': value['organisationId'],
    };
}

