/* tslint:disable */
/* eslint-disable */
/**
 * ISOK API
 * Openapi of isok api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganisationSimpleView
 */
export interface OrganisationSimpleView {
    /**
     * 
     * @type {string}
     * @memberof OrganisationSimpleView
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationSimpleView
     */
    name: string;
    /**
     * 
     * @type {{ [key: string]: string | null; }}
     * @memberof OrganisationSimpleView
     */
    tags: { [key: string]: string | null; };
}

/**
 * Check if a given object implements the OrganisationSimpleView interface.
 */
export function instanceOfOrganisationSimpleView(value: object): value is OrganisationSimpleView {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    return true;
}

export function OrganisationSimpleViewFromJSON(json: any): OrganisationSimpleView {
    return OrganisationSimpleViewFromJSONTyped(json, false);
}

export function OrganisationSimpleViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationSimpleView {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'tags': json['tags'],
    };
}

export function OrganisationSimpleViewToJSON(json: any): OrganisationSimpleView {
    return OrganisationSimpleViewToJSONTyped(json, false);
}

export function OrganisationSimpleViewToJSONTyped(value?: OrganisationSimpleView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'tags': value['tags'],
    };
}

