/* tslint:disable */
/* eslint-disable */
/**
 * ISOK API
 * Openapi of isok api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganisationMemberPath
 */
export interface OrganisationMemberPath {
    /**
     * 
     * @type {string}
     * @memberof OrganisationMemberPath
     */
    organisationId: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationMemberPath
     */
    userId: string;
}

/**
 * Check if a given object implements the OrganisationMemberPath interface.
 */
export function instanceOfOrganisationMemberPath(value: object): value is OrganisationMemberPath {
    if (!('organisationId' in value) || value['organisationId'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function OrganisationMemberPathFromJSON(json: any): OrganisationMemberPath {
    return OrganisationMemberPathFromJSONTyped(json, false);
}

export function OrganisationMemberPathFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationMemberPath {
    if (json == null) {
        return json;
    }
    return {
        
        'organisationId': json['organisation_id'],
        'userId': json['user_id'],
    };
}

export function OrganisationMemberPathToJSON(json: any): OrganisationMemberPath {
    return OrganisationMemberPathToJSONTyped(json, false);
}

export function OrganisationMemberPathToJSONTyped(value?: OrganisationMemberPath | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organisation_id': value['organisationId'],
        'user_id': value['userId'],
    };
}

