/* tslint:disable */
/* eslint-disable */
/**
 * ISOK API
 * Openapi of isok api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchUser
 */
export interface PatchUser {
    /**
     * 
     * @type {string}
     * @memberof PatchUser
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchUser
     */
    password?: string;
}

/**
 * Check if a given object implements the PatchUser interface.
 */
export function instanceOfPatchUser(value: object): value is PatchUser {
    return true;
}

export function PatchUserFromJSON(json: any): PatchUser {
    return PatchUserFromJSONTyped(json, false);
}

export function PatchUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchUser {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function PatchUserToJSON(json: any): PatchUser {
    return PatchUserToJSONTyped(json, false);
}

export function PatchUserToJSONTyped(value?: PatchUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

