/* tslint:disable */
/* eslint-disable */
/**
 * ISOK API
 * Openapi of isok api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TenantCheckPath
 */
export interface TenantCheckPath {
    /**
     * 
     * @type {string}
     * @memberof TenantCheckPath
     */
    checkId: string;
    /**
     * 
     * @type {string}
     * @memberof TenantCheckPath
     */
    tenant: string;
}

/**
 * Check if a given object implements the TenantCheckPath interface.
 */
export function instanceOfTenantCheckPath(value: object): value is TenantCheckPath {
    if (!('checkId' in value) || value['checkId'] === undefined) return false;
    if (!('tenant' in value) || value['tenant'] === undefined) return false;
    return true;
}

export function TenantCheckPathFromJSON(json: any): TenantCheckPath {
    return TenantCheckPathFromJSONTyped(json, false);
}

export function TenantCheckPathFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantCheckPath {
    if (json == null) {
        return json;
    }
    return {
        
        'checkId': json['check_id'],
        'tenant': json['tenant'],
    };
}

export function TenantCheckPathToJSON(json: any): TenantCheckPath {
    return TenantCheckPathToJSONTyped(json, false);
}

export function TenantCheckPathToJSONTyped(value?: TenantCheckPath | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'check_id': value['checkId'],
        'tenant': value['tenant'],
    };
}

