/* tslint:disable */
/* eslint-disable */
/**
 * ISOK API
 * Openapi of isok api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TenantPath
 */
export interface TenantPath {
    /**
     * 
     * @type {string}
     * @memberof TenantPath
     */
    tenant: string;
}

/**
 * Check if a given object implements the TenantPath interface.
 */
export function instanceOfTenantPath(value: object): value is TenantPath {
    if (!('tenant' in value) || value['tenant'] === undefined) return false;
    return true;
}

export function TenantPathFromJSON(json: any): TenantPath {
    return TenantPathFromJSONTyped(json, false);
}

export function TenantPathFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantPath {
    if (json == null) {
        return json;
    }
    return {
        
        'tenant': json['tenant'],
    };
}

export function TenantPathToJSON(json: any): TenantPath {
    return TenantPathToJSONTyped(json, false);
}

export function TenantPathToJSONTyped(value?: TenantPath | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tenant': value['tenant'],
    };
}

