/* tslint:disable */
/* eslint-disable */
/**
 * ISOK API
 * Openapi of isok api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserSimpleView
 */
export interface UserSimpleView {
    /**
     * 
     * @type {string}
     * @memberof UserSimpleView
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserSimpleView
     */
    id: string;
}

/**
 * Check if a given object implements the UserSimpleView interface.
 */
export function instanceOfUserSimpleView(value: object): value is UserSimpleView {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function UserSimpleViewFromJSON(json: any): UserSimpleView {
    return UserSimpleViewFromJSONTyped(json, false);
}

export function UserSimpleViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSimpleView {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'id': json['id'],
    };
}

export function UserSimpleViewToJSON(json: any): UserSimpleView {
    return UserSimpleViewToJSONTyped(json, false);
}

export function UserSimpleViewToJSONTyped(value?: UserSimpleView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'id': value['id'],
    };
}

