/* tslint:disable */
/* eslint-disable */
/**
 * ISOK API
 * Openapi of isok api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserView
 */
export interface UserView {
    /**
     * 
     * @type {string}
     * @memberof UserView
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserView
     */
    id: string;
    /**
     * 
     * @type {{ [key: string]: string | null; }}
     * @memberof UserView
     */
    tags: { [key: string]: string | null; };
}

/**
 * Check if a given object implements the UserView interface.
 */
export function instanceOfUserView(value: object): value is UserView {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    return true;
}

export function UserViewFromJSON(json: any): UserView {
    return UserViewFromJSONTyped(json, false);
}

export function UserViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserView {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'id': json['id'],
        'tags': json['tags'],
    };
}

export function UserViewToJSON(json: any): UserView {
    return UserViewToJSONTyped(json, false);
}

export function UserViewToJSONTyped(value?: UserView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'id': value['id'],
        'tags': value['tags'],
    };
}

