import './components/button-menu'
import './components/menu'
import './components/top-page'
import './components/barchart'
import './components/check'
import './components/domain-checks'
import './components/popup-new-check'

import './app'
import './pages/home'
import './pages/connection'
import './pages/register'